### ISSUE TITLE
Windows Specific Code

### ISSUE THREAD

**Issue by Intecpsp** [SimonCropp/LocalDb#396]
The below code is Windows only and cannot be run on MacOS. 
`Access Control List (ACL) APIs are part of resource management on Windows and are not supported on this platform.`

   at System.IO.FileSystemAclExtensions.GetAccessControl(DirectoryInfo directoryInfo)
   at FileExtensions.ResetAccess(DirectoryInfo directoryInfo) in C:\projects\localdb\src\LocalDb\FileExtensions.cs:line 25
   at Wrapper..ctor(Func`2 buildConnection, String instance, String directory, UInt16 size, Nullable`1 existingTemplate, Func`2 callback) in C:\projects\localdb\src\LocalDb\Wrapper.cs:line 69
   at EfLocalDb.SqlInstance`1..ctor(ConstructInstance`1 constructInstance, TemplateFromConnection`1 buildTemplate, Nullable`1 storage, Nullable`1 timestamp, UInt16 templateSize, Nullable`1 existingTemplate, Callback`1 callback, Action`1 sqlOptionsBuilder) in C:\projects\localdb\src\EfLocalDb\SqlInstance.cs:line 122
   at EfLocalDb.SqlInstance`1..ctor(ConstructInstance`1 constructInstance, TemplateFromContext`1 buildTemplate, Nullable`1 storage, Nullable`1 timestamp, UInt16 templateSize, Nullable`1 existingTemplate, Callback`1 callback, Action`1 sqlOptionsBuilder) in C:\projects\localdb\src\EfLocalDb\SqlInstance.cs:line 64

I found this issue when trying to run the SampleWeb project in GraphQL.EntityFramework on my Mac. Is this really needed or can it be achieved in another way? 

https://github.com/SimonCropp/LocalDb/blob/46c7d5566ce3b7328ad6ebe559b455d8860bfcc6/src/LocalDb/FileExtensions.cs#L25

**Comment by SimonCropp** [comment]
afaik there is no localdb on mac. so not much worth changing in this context

**Comment by Intecpsp** [comment]
I see this now, I didn't know it wasn't on Mac
