### ISSUE TITLE
Issues when running tests in parallel in a solution with multiple test projects using the EfLocalDb

### ISSUE THREAD

**Issue by KGergo88** [SimonCropp/LocalDb#657]
First of all, thank you for your work on developing the LocalDb project.

#### Describe the bug

I have a Solution with multiple xUnit test projects using Entity Framework Core.
The documentation suggests that the test classes inherit from a `TestBase` class that has a static `SqlInstance` object.
I have copied the code for the base class from [the documentation](https://github.com/SimonCropp/LocalDb/blob/main/pages/ef-usage.md#static-constructor-in-test-base) and put it into a common test utility project that is referenced by all the test projects.

If I run the tests in VisualStudio by turning the `Test Explorer / Options / Run Tests in Parallel` then everything seems to be ok.
When running them parallel, I keep getting error messages that suggest me that there is a race condition somewhere:

```
Message: 
System.Exception : Failed to execute SQL command.
commandText: declare @command nvarchar(max)
set @command = ''

select @command = @command
+ '
    alter database [' + [name] + '] set single_user with rollback immediate;
    alter database [' + [name] + '] set multi_user;
    alter database [' + [name] + '] set offline;
'
from master.sys.databases
where [name] not in ('master', 'model', 'msdb', 'tempdb', 'template');
execute sp_executesql @command
connectionString: Data Source=(LocalDb)\EfLocalDbTestDbContext;Database=master;Pooling=true

---- Microsoft.Data.SqlClient.SqlException : ALTER DATABASE statement failed.
ALTER DATABASE statement failed.
ALTER DATABASE statement failed.
ALTER DATABASE statement failed.
ALTER DATABASE statement failed.
ALTER DATABASE statement failed.
ALTER DATABASE statement failed.
ALTER DATABASE statement failed.
ALTER DATABASE statement failed.
ALTER DATABASE statement failed.
ALTER DATABASE statement failed.
ALTER DATABASE statement failed.
ALTER DATABASE statement failed.
ALTER DATABASE statement failed.
ALTER DATABASE statement failed.
Cannot continue the execution because the session is in the kill state.
A severe error occurred on the current command.  The results, if any, should be discarded.

  Stack Trace: 
SqlExtensions.ExecuteCommandAsync(DbConnection connection, String commandText) line 31
Wrapper.CreateAndDetachTemplate(DateTime timestamp, Func`2 buildTemplate, Boolean rebuild, Boolean optimize) line 229
Wrapper.CreateAndDetachTemplate(DateTime timestamp, Func`2 buildTemplate, Boolean rebuild, Boolean optimize) line 229
Wrapper.CreateAndDetachTemplate(DateTime timestamp, Func`2 buildTemplate, Boolean rebuild, Boolean optimize) line 229
Wrapper.CreateDatabaseFromTemplate(String name) line 77
SqlInstance`1.Build(String dbName, IEnumerable`1 data) line 73
SqlInstance`1.Build(String dbName, IEnumerable`1 data) line 73
TestClassA2.Test1() line 11
TestClassA1.Test1() line 11
--- End of stack trace from previous location ---
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
<>c.<InternalExecuteNonQueryAsync>b__193_1(IAsyncResult asyncResult)
TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
SqlExtensions.ExecuteCommandAsync(DbConnection connection, String commandText) line 18
SqlExtensions.ExecuteCommandAsync(DbConnection connection, String commandText) line 18
```

If I then delete all the content from the LocalDb folder, then I get a different error message when running the tests parallel in Visual Studio:

```
 EfLocalDbTest.TestProjectA.TestClassA1.Test1
   Source: TestClassA1.cs line 9
   Duration: 12.6 sec

  Message: 
System.Exception : Failed to execute SQL command.
commandText: if db_id('template') is not null
begin
  execute sp_detach_db 'template', 'true';
end;
create database template on
(
    name = template,
    filename = 'C:\Users\<UserName>\AppData\Local\Temp\LocalDb\EfLocalDbTestDbContext\template.mdf',
    fileGrowth = 100KB
)
log on
(
    name = template_log,
    filename = 'C:\Users\<UserName>\AppData\Local\Temp\LocalDb\EfLocalDbTestDbContext\template_log.ldf',
    size = 512KB,
    filegrowth = 100KB
);
connectionString: Data Source=(LocalDb)\EfLocalDbTestDbContext;Database=master;Pooling=true

---- Microsoft.Data.SqlClient.SqlException : Transaction (Process ID 54) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

  Stack Trace: 
SqlExtensions.ExecuteCommandAsync(DbConnection connection, String commandText) line 31
Wrapper.Rebuild(DateTime timestamp, Func`2 buildTemplate, DbConnection masterConnection) line 242
Wrapper.CreateAndDetachTemplate(DateTime timestamp, Func`2 buildTemplate, Boolean rebuild, Boolean optimize) line 226
Wrapper.CreateAndDetachTemplate(DateTime timestamp, Func`2 buildTemplate, Boolean rebuild, Boolean optimize) line 229
Wrapper.CreateAndDetachTemplate(DateTime timestamp, Func`2 buildTemplate, Boolean rebuild, Boolean optimize) line 229
Wrapper.CreateDatabaseFromTemplate(String name) line 77
Wrapper.CreateDatabaseFromTemplate(String name) line 77
SqlInstance`1.Build(String dbName, IEnumerable`1 data) line 73
TestClassA1.Test1() line 11
TestClassA2.Test1() line 11
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
<>c.<InternalExecuteNonQueryAsync>b__193_1(IAsyncResult asyncResult)
TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
SqlExtensions.ExecuteCommandAsync(DbConnection connection, String commandText) line 18
SqlExtensions.ExecuteCommandAsync(DbConnection connection, String commandText) line 18
```

When running the tests from the CLI with `dotnet test` the issue is present, but the error message is different:

```
$ dotnet test
  Determining projects to restore...
  All projects are up-to-date for restore.
  Data -> C:\Work\EfLocalDbTest\Data\bin\Debug\net8.0\Data.dll
  TestCommon -> C:\Work\EfLocalDbTest\TestCommon\bin\Debug\net8.0\TestCommon.dll
Test run for C:\Work\EfLocalDbTest\TestCommon\bin\Debug\net8.0\TestCommon.dll (.NETCoreApp,Version=v8.0)
VSTest version 17.11.1 (x64)

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
No test is available in C:\Work\EfLocalDbTest\TestCommon\bin\Debug\net8.0\TestCommon.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Additionally, path to test adapters can be specified using /TestAdapterPath command. Example  /TestAdapterPath:<pathToCustomAdapters>.
  TestProjectB -> C:\Work\EfLocalDbTest\TestProjectB\bin\Debug\net8.0\TestProjectB.dll
  TestProjectA -> C:\Work\EfLocalDbTest\TestProjectA\bin\Debug\net8.0\TestProjectA.dll
Test run for C:\Work\EfLocalDbTest\TestProjectB\bin\Debug\net8.0\TestProjectB.dll (.NETCoreApp,Version=v8.0)
Test run for C:\Work\EfLocalDbTest\TestProjectA\bin\Debug\net8.0\TestProjectA.dll (.NETCoreApp,Version=v8.0)
VSTest version 17.11.1 (x64)
VSTest version 17.11.1 (x64)


Starting test execution, please wait...
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:12.58]     EfLocalDbTest.TestProjectB.TestClassB1.Test1 [FAIL]
[xUnit.net 00:00:12.58]     EfLocalDbTest.TestProjectB.TestClassB2.Test1 [FAIL]
  Failed EfLocalDbTest.TestProjectB.TestClassB1.Test1 [12 s]
  Error Message:
   System.Exception : Failed to execute SQL command.
commandText: if db_id('template') is not null
begin
  execute sp_detach_db 'template', 'true';
end;
create database template on
(
    name = template,
    filename = 'C:\Users\<UserName>\AppData\Local\Temp\LocalDb\EfLocalDbTestDbContext\template.mdf',
    fileGrowth = 100KB
)
log on
(
    name = template_log,
    filename = 'C:\Users\<UserName>\AppData\Local\Temp\LocalDb\EfLocalDbTestDbContext\template_log.ldf',
    size = 512KB,
    filegrowth = 100KB
);
connectionString: Data Source=(LocalDb)\EfLocalDbTestDbContext;Database=master;Pooling=true

---- Microsoft.Data.SqlClient.SqlException : Transaction (Process ID 54) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
  Stack Trace:
     at SqlExtensions.ExecuteCommandAsync(DbConnection connection, String commandText) in C:\projects\localdb\src\LocalDb\SqlExtensions.cs:line 31
   at Wrapper.Rebuild(DateTime timestamp, Func`2 buildTemplate, DbConnection masterConnection) in C:\projects\localdb\src\LocalDb\Wrapper.cs:line 242
   at Wrapper.CreateAndDetachTemplate(DateTime timestamp, Func`2 buildTemplate, Boolean rebuild, Boolean optimize) in C:\projects\localdb\src\LocalDb\Wrapper.cs:line 226
   at Wrapper.CreateAndDetachTemplate(DateTime timestamp, Func`2 buildTemplate, Boolean rebuild, Boolean optimize) in C:\projects\localdb\src\LocalDb\Wrapper.cs:line 229
   at Wrapper.CreateAndDetachTemplate(DateTime timestamp, Func`2 buildTemplate, Boolean rebuild, Boolean optimize) in C:\projects\localdb\src\LocalDb\Wrapper.cs:line 229
   at Wrapper.CreateDatabaseFromTemplate(String name) in C:\projects\localdb\src\LocalDb\Wrapper.cs:line 77
   at EfLocalDb.SqlInstance`1.Build(String dbName, IEnumerable`1 data) in C:\projects\localdb\src\EfLocalDb\SqlInstance_Build.cs:line 73
   at EfLocalDb.SqlInstance`1.Build(String dbName, IEnumerable`1 data) in C:\projects\localdb\src\EfLocalDb\SqlInstance_Build.cs:line 73
   at EfLocalDbTest.TestProjectB.TestClassB1.Test1() in C:\Work\EfLocalDbTest\TestProjectB\TestClassB1.cs:line 11
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<InternalExecuteNonQueryAsync>b__193_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at SqlExtensions.ExecuteCommandAsync(DbConnection connection, String commandText) in C:\projects\localdb\src\LocalDb\SqlExtensions.cs:line 18
   at SqlExtensions.ExecuteCommandAsync(DbConnection connection, String commandText) in C:\projects\localdb\src\LocalDb\SqlExtensions.cs:line 18
  Failed EfLocalDbTest.TestProjectB.TestClassB2.Test1 [12 s]
  Error Message:
   System.Exception : Failed to execute SQL command.
commandText: if db_id('template') is not null
begin
  execute sp_detach_db 'template', 'true';
end;
create database template on
(
    name = template,
    filename = 'C:\Users\<UserName>\AppData\Local\Temp\LocalDb\EfLocalDbTestDbContext\template.mdf',
    fileGrowth = 100KB
)
log on
(
    name = template_log,
    filename = 'C:\Users\<UserName>\AppData\Local\Temp\LocalDb\EfLocalDbTestDbContext\template_log.ldf',
    size = 512KB,
    filegrowth = 100KB
);
connectionString: Data Source=(LocalDb)\EfLocalDbTestDbContext;Database=master;Pooling=true

---- Microsoft.Data.SqlClient.SqlException : Transaction (Process ID 54) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
  Stack Trace:
     at SqlExtensions.ExecuteCommandAsync(DbConnection connection, String commandText) in C:\projects\localdb\src\LocalDb\SqlExtensions.cs:line 31
   at Wrapper.Rebuild(DateTime timestamp, Func`2 buildTemplate, DbConnection masterConnection) in C:\projects\localdb\src\LocalDb\Wrapper.cs:line 242
   at Wrapper.CreateAndDetachTemplate(DateTime timestamp, Func`2 buildTemplate, Boolean rebuild, Boolean optimize) in C:\projects\localdb\src\LocalDb\Wrapper.cs:line 226
   at Wrapper.CreateAndDetachTemplate(DateTime timestamp, Func`2 buildTemplate, Boolean rebuild, Boolean optimize) in C:\projects\localdb\src\LocalDb\Wrapper.cs:line 229
   at Wrapper.CreateAndDetachTemplate(DateTime timestamp, Func`2 buildTemplate, Boolean rebuild, Boolean optimize) in C:\projects\localdb\src\LocalDb\Wrapper.cs:line 229
   at Wrapper.CreateDatabaseFromTemplate(String name) in C:\projects\localdb\src\LocalDb\Wrapper.cs:line 77
   at EfLocalDb.SqlInstance`1.Build(String dbName, IEnumerable`1 data) in C:\projects\localdb\src\EfLocalDb\SqlInstance_Build.cs:line 73
   at EfLocalDb.SqlInstance`1.Build(String dbName, IEnumerable`1 data) in C:\projects\localdb\src\EfLocalDb\SqlInstance_Build.cs:line 73
   at EfLocalDbTest.TestProjectB.TestClassB1.Test1() in C:\Work\EfLocalDbTest\TestProjectB\TestClassB1.cs:line 11
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<InternalExecuteNonQueryAsync>b__193_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at SqlExtensions.ExecuteCommandAsync(DbConnection connection, String commandText) in C:\projects\localdb\src\LocalDb\SqlExtensions.cs:line 18
   at SqlExtensions.ExecuteCommandAsync(DbConnection connection, String commandText) in C:\projects\localdb\src\LocalDb\SqlExtensions.cs:line 18

[xUnit.net 00:00:12.64]     EfLocalDbTest.TestProjectA.TestClassA1.Test1 [FAIL]
Failed!  - Failed:     2, Passed:     0, Skipped:     0, Total:     2, Duration: 3 ms - TestProjectB.dll (net8.0)
[xUnit.net 00:00:12.65]     EfLocalDbTest.TestProjectA.TestClassA2.Test1 [FAIL]
  Failed EfLocalDbTest.TestProjectA.TestClassA1.Test1 [12 s]
  Error Message:
   System.Exception : Failed to execute SQL command.
commandText: if db_id('template') is not null
begin
  execute sp_detach_db 'template', 'true';
end;
create database template on
(
    name = template,
    filename = 'C:\Users\<UserName>\AppData\Local\Temp\LocalDb\EfLocalDbTestDbContext\template.mdf',
    fileGrowth = 100KB
)
log on
(
    name = template_log,
    filename = 'C:\Users\<UserName>\AppData\Local\Temp\LocalDb\EfLocalDbTestDbContext\template_log.ldf',
    size = 512KB,
    filegrowth = 100KB
);
connectionString: Data Source=(LocalDb)\EfLocalDbTestDbContext;Database=master;Pooling=true

---- Microsoft.Data.SqlClient.SqlException : Unable to open the physical file "C:\Users\<UserName>\AppData\Local\Temp\LocalDb\EfLocalDbTestDbContext\template.mdf". Operating system error 2: "2(The system cannot find the file specified.)".
CREATE DATABASE failed. Some file names listed could not be created. Check related errors.
  Stack Trace:
     at SqlExtensions.ExecuteCommandAsync(DbConnection connection, String commandText) in C:\projects\localdb\src\LocalDb\SqlExtensions.cs:line 31
   at Wrapper.Rebuild(DateTime timestamp, Func`2 buildTemplate, DbConnection masterConnection) in C:\projects\localdb\src\LocalDb\Wrapper.cs:line 242
   at Wrapper.CreateAndDetachTemplate(DateTime timestamp, Func`2 buildTemplate, Boolean rebuild, Boolean optimize) in C:\projects\localdb\src\LocalDb\Wrapper.cs:line 226
   at Wrapper.CreateAndDetachTemplate(DateTime timestamp, Func`2 buildTemplate, Boolean rebuild, Boolean optimize) in C:\projects\localdb\src\LocalDb\Wrapper.cs:line 229
   at Wrapper.CreateAndDetachTemplate(DateTime timestamp, Func`2 buildTemplate, Boolean rebuild, Boolean optimize) in C:\projects\localdb\src\LocalDb\Wrapper.cs:line 229
   at Wrapper.CreateDatabaseFromTemplate(String name) in C:\projects\localdb\src\LocalDb\Wrapper.cs:line 77
   at Wrapper.CreateDatabaseFromTemplate(String name) in C:\projects\localdb\src\LocalDb\Wrapper.cs:line 77
   at EfLocalDb.SqlInstance`1.Build(String dbName, IEnumerable`1 data) in C:\projects\localdb\src\EfLocalDb\SqlInstance_Build.cs:line 73
   at EfLocalDbTest.TestProjectA.TestClassA2.Test1() in C:\Work\EfLocalDbTest\TestProjectA\TestClassA2.cs:line 11
   at EfLocalDbTest.TestProjectA.TestClassA1.Test1() in C:\Work\EfLocalDbTest\TestProjectA\TestClassA1.cs:line 11
--- End of stack trace from previous location ---
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<InternalExecuteNonQueryAsync>b__193_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at SqlExtensions.ExecuteCommandAsync(DbConnection connection, String commandText) in C:\projects\localdb\src\LocalDb\SqlExtensions.cs:line 18
   at SqlExtensions.ExecuteCommandAsync(DbConnection connection, String commandText) in C:\projects\localdb\src\LocalDb\SqlExtensions.cs:line 18
  Failed EfLocalDbTest.TestProjectA.TestClassA2.Test1 [12 s]
  Error Message:
   System.Exception : Failed to execute SQL command.
commandText: if db_id('template') is not null
begin
  execute sp_detach_db 'template', 'true';
end;
create database template on
(
    name = template,
    filename = 'C:\Users\<UserName>\AppData\Local\Temp\LocalDb\EfLocalDbTestDbContext\template.mdf',
    fileGrowth = 100KB
)
log on
(
    name = template_log,
    filename = 'C:\Users\<UserName>\AppData\Local\Temp\LocalDb\EfLocalDbTestDbContext\template_log.ldf',
    size = 512KB,
    filegrowth = 100KB
);
connectionString: Data Source=(LocalDb)\EfLocalDbTestDbContext;Database=master;Pooling=true

---- Microsoft.Data.SqlClient.SqlException : Unable to open the physical file "C:\Users\<UserName>\AppData\Local\Temp\LocalDb\EfLocalDbTestDbContext\template.mdf". Operating system error 2: "2(The system cannot find the file specified.)".
CREATE DATABASE failed. Some file names listed could not be created. Check related errors.
  Stack Trace:
     at SqlExtensions.ExecuteCommandAsync(DbConnection connection, String commandText) in C:\projects\localdb\src\LocalDb\SqlExtensions.cs:line 31
   at Wrapper.Rebuild(DateTime timestamp, Func`2 buildTemplate, DbConnection masterConnection) in C:\projects\localdb\src\LocalDb\Wrapper.cs:line 242
   at Wrapper.CreateAndDetachTemplate(DateTime timestamp, Func`2 buildTemplate, Boolean rebuild, Boolean optimize) in C:\projects\localdb\src\LocalDb\Wrapper.cs:line 226
   at Wrapper.CreateAndDetachTemplate(DateTime timestamp, Func`2 buildTemplate, Boolean rebuild, Boolean optimize) in C:\projects\localdb\src\LocalDb\Wrapper.cs:line 229
   at Wrapper.CreateAndDetachTemplate(DateTime timestamp, Func`2 buildTemplate, Boolean rebuild, Boolean optimize) in C:\projects\localdb\src\LocalDb\Wrapper.cs:line 229
   at Wrapper.CreateDatabaseFromTemplate(String name) in C:\projects\localdb\src\LocalDb\Wrapper.cs:line 77
   at Wrapper.CreateDatabaseFromTemplate(String name) in C:\projects\localdb\src\LocalDb\Wrapper.cs:line 77
   at EfLocalDb.SqlInstance`1.Build(String dbName, IEnumerable`1 data) in C:\projects\localdb\src\EfLocalDb\SqlInstance_Build.cs:line 73
   at EfLocalDbTest.TestProjectA.TestClassA2.Test1() in C:\Work\EfLocalDbTest\TestProjectA\TestClassA2.cs:line 11
   at EfLocalDbTest.TestProjectA.TestClassA1.Test1() in C:\Work\EfLocalDbTest\TestProjectA\TestClassA1.cs:line 11
--- End of stack trace from previous location ---
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<InternalExecuteNonQueryAsync>b__193_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at SqlExtensions.ExecuteCommandAsync(DbConnection connection, String commandText) in C:\projects\localdb\src\LocalDb\SqlExtensions.cs:line 18
   at SqlExtensions.ExecuteCommandAsync(DbConnection connection, String commandText) in C:\projects\localdb\src\LocalDb\SqlExtensions.cs:line 18

Failed!  - Failed:     2, Passed:     0, Skipped:     0, Total:     2, Duration: 3 ms - TestProjectA.dll (net8.0)

Workload updates are available. Run `dotnet workload list` for more information.
```

If I run the test in series in Visual Studio to create the template files and then run the `dotnet test` again, I get the same error message as in Visual Studio:
```
...
---- Microsoft.Data.SqlClient.SqlException : ALTER DATABASE statement failed.
ALTER DATABASE statement failed.
ALTER DATABASE statement failed.
Cannot continue the execution because the session is in the kill state.
A severe error occurred on the current command.  The results, if any, should be discarded.
  Stack Trace:
     at SqlExtensions.ExecuteCommandAsync(DbConnection connection, String commandText) in C:\projects\localdb\src\LocalDb\SqlExtensions.cs:line 31
...
```

Used versions:
 - NuGet packages: please see the linked GitHub repository in the `Minimal Repro` section
 - Microsoft Visual Studio: Microsoft Visual Studio Professional 2022, Version 17.11.5
 - VSTest: version 17.11.1 (x64)
 - Microsoft SQL Server 2022 LocalDB 16.0.1000.6

#### Minimal Repro

I have created a public GitHub repository where the issue can be reproduced:
https://github.com/KGergo88/EfLocalDbTest

#### Submit a PR that fixes the bug

No PR was created.

#### Questions

- Did I misunderstood the documentation?
- Do I have an issue with the number of `SqlInstance` objects created?
- Is this kind of setup possible with `EfLocalDb`?
- If none of the above, how do I make this work?

Thank you in advance for your help.

**Comment by SimonCropp** [comment]
can u share your exact testbase code

**Comment by KGergo88** [comment]
Sure, it is a 1 to 1 copy of the one suggested by the documentation:
https://github.com/KGergo88/EfLocalDbTest/blob/main/TestCommon/TestBase.cs

**Comment by KGergo88** [comment]
Since then I have made it work, altough not the way I originally wanted to.

I will leave it here as it might help others:
The test structure where multiple projects use LocalDb with a TestBase that is defined in a common project does not work. The workaround is to have all the tests that use LocalDb in the same test project and have the TestBase class also in this project. In order to achieve this I have created a single test project for integration tests (these are able to use LocalDb) and other unittest projects that are not using LocalDb.

**Comment by SimonCropp** [comment]
the naming convention for that base class uses the dbcontext type alone to work out the db name. if u have multiple different test assemblies creating instance of SqlInstance they will conflict. u need to ensure that the name is distinct using the storage parameter of the SqlInstance  constructor

https://github.com/SimonCropp/LocalDb/blob/main/pages/directory-and-name-resolution.md#for-entityframework
